import { Header } from '../components/Header'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

const roboto = Roboto({ 
  subsets: ['latin'], 
  weight: '400'
})

export const metadata: Metadata = {
  title: 'MovieTicket',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className={roboto.className}>
        <Header/>
        <main className='bg-gray-950 min-w-screen min-h-screen text-gray-100'>
          {children}
        </main>
    </div>
  )
}
