import { Header } from "@/components/Header"
import './globals.css'
import { Roboto } from 'next/font/google'

export const metadata = {
  title: 'MovieTicket',
  description: 'Generated by create next app',
}

const roboto = Roboto({ 
  subsets: ['latin'], 
  weight: '400'
})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header/>
        <main className='bg-gray-950 min-w-screen min-h-screen text-gray-100'>
          {children}
        </main>
      </body>
    </html>
  )
}
